# Generated by Django 4.1.13 on 2024-06-21 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='myip',
            name='my_tickey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ticket'),
        ),
    ]
