# Generated by Django 4.1.13 on 2024-06-21 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ticket_myip_my_tickey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myip',
            old_name='my_tickey',
            new_name='my_ticket',
        ),
    ]
