# Generated by Django 4.1.13 on 2024-06-21 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_my_tickey_myip_my_ticket'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ticket',
            new_name='ticket_info',
        ),
    ]
